### PR TITLE
Tag element templates with Polymer.html

### LINKED ISSUE #239: Update template conversion to use Polymer.html template tag
Assuming this proposal goes through: https://github.com/Polymer/polymer/issues/4937

We'll want to output:

```js
import {html, Element as PolymerElement} from '@polymer/polymer/polymer.js';

class MyElement extends PolymerElement {
  template = html`...`;
}
```

### PR DESCRIPTION
**Pull request by justinfagnani**
Fixes #239

### CODE REVIEW

**Comment by justinfagnani** [comment]
Er, don't review yet... I forgot some things

**Comment by justinfagnani** [comment]
Ok, updated some unit tests to make sure that the added `Polymer.html` references were indeed being converted properly to JS imports. All seems well there.

I still haven't regenerated the fixtures due to what looks like bad fixture generation with my repo. @FredKSchott could you try to see what happens with fixture generation with a clean checkout on your end?

**Comment by FredKSchott** [comment]
LMK when this is ready for another review

**Comment by justinfagnani** [comment]
@FredKSchott rebase, removed workarounds for not having html-tag.html, and ready for review again.

**Comment by justinfagnani** [comment]
I was thinking of that yesterday, but had already generated these commits and the change was relatively small. Good idea though.

**Pull request merged**
