### PR TITLE
add test-helpers as a known js file

### PR DESCRIPTION
**Pull request by e111077**
fixes paper-input

### CODE REVIEW

**Comment by FredKSchott** [comment]
@e111077 hmm, how did you format these files? Did you run `npm run format`? Can you try it with a fresh dependency `rm -rf node_modules/ && npm install`? When I run format I don't get all these changes.

**Comment by e111077** [comment]
Didn't have clang-format extension. You caught me in the middle of undoing everything ever

**Comment by e111077** [comment]
@FredKSchott fixed. Ready for review

**Comment by FredKSchott** [comment]
LGTM! Nice find! (Travis seems to have timed out unrelated to this change)

**Pull request merged**
