### PR TITLE
Add files property in package.json to reduce package size

### PR DESCRIPTION
**Pull request by web-padawan**
See for example the recently merged webcomponents/webcomponentsjs#929

@bicknellr please take a look if these files should be enough, or am I missing something?

---
This change is [Reviewable](https://reviewable.io/reviews/polymer/polymer-modulizer/455)

### CODE REVIEW

**Comment by justinfagnani** [comment]
How much does this reduce the package size? The source shouldn't be that large.

**Comment by web-padawan** [comment]
This is expected to ensure that no test fixturest etc get published occasionally.

**Comment by bicknellr** [comment]
Should `src/` not also be in this list?

**Comment by web-padawan** [comment]
I used the code from analyzer: https://github.com/Polymer/tools/blob/master/packages/analyzer/package.json

Feel free to modify this PR if you think `src` should be also published.

**Comment by justinfagnani** [comment]
Opened https://github.com/Polymer/tools/pull/573 in the monorepo

**Pull request closed without merging**
