### PR TITLE
format all files with vscode

### PR DESCRIPTION
**Pull request by e111077**
this project includes a `.vscode/settings.json` which specifies format on save. This means that if I want to make a one-line change to a file, then it is muddled with all of these formatting changes.

Alternative to this PR is to simply set that flag to false.

### CODE REVIEW

**Comment by stramel** [comment]
:+1: I ALWAYS have to run the formatter after I save files in vscode before I submit PR.

**Comment by rictic** [comment]
We auto-format with clang-format. There's a clang-format vscode plugin, and we've got a script to run the formatter over all files that you can run with: `npm run format`

Maybe we should add clang-format to the vscode recommended plugins for this repo? https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions

**Comment by stramel** [comment]
Probably would be good for any of the repos where you are using clang formatter to maintain the formatting and have the vscode settings.

**Comment by TimvdLippe** [comment]
You can do that with `git diff --exitcode`. We use that in Polymer/Polymer: https://github.com/Polymer/polymer/pull/5003

**Comment by stramel** [comment]
@timvdlippe I thinking you just add it to the precommit hook. So code doesn't ever get committed without the formatting being ran. Something like [Husky](https://github.com/typicode/husky) makes that really easy.

**Comment by e111077** [comment]
got clang compiler. Closing PR opening issue for continuation of this discussion

**Pull request closed without merging**
